[package]
name = "scale-the-tower"
version = "0.1.0"
edition = "2021"

[dependencies]
cgmath = "0.18.0"
gl = "0.14.0"
glfw = "0.53.0"
png = "0.17.10"
rand = "0.8.5"
rodio = "0.17.3"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"
